Module4 task1
htmlacademy-nodejs/1123341-buy-and-sell-3 pull request #9
Opened 2021-01-26 18:58 UTC by tyort

2021-01-31 19:57 UTC, tsapko3628 requested changes

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/api/index.js
> +})();
app будет экспортирован до того как завершиться эта загрузка. Во время использования app, роуты могут быть ещё не добавлены. В случае ошибки в этой функции, она не будет обработана. в 12+ версии ноды, приложение сразу же завершиться.
Как это можно исправить:
Можно возвращать асинхронную функцию (или её результат (промис)) из модуля. Тогда, там где он будет импортирован, можно будет дождаться её завершения и корркетно использовать роутер. Лучше, чтобы в этой же функции возвращался сам роутер (соответственно и создавался бы в ней)

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/api/search.js
> +const route = new Router();
роутер лучше создать внутри функции. Если функция будет вызвана несколько раз, будет использоваться один роутер

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/api/search.js
> +const route = new Router();
Несколько вызовов этой функции может понадобиться в тестах

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/category.js
> +    return [...categories];
new Set(this._offers.flatMap(offer => offer.category));

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/comment.js
> +  }
nit: Почему drop если это самый настоящий delete? )

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/offer.js
> +      .assign({id: nanoid(MAX_ID_LENGTH), comments: []}, offer);
```js
const newOffer = {
  id: nanoid(MAX_ID_LENGTH),
  comments: [],
   ...offer
};
```

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/offer.js
> +  drop(id) {
Такие методы все таки принято называть delete. 
Функция это действие, то есть её название расценивается как глагол. drop -- больше бросить/уронить чем удалить.

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/offer.js
> +  drop(id) {
Касается всех мест в pull-request-е

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/offer.js
> +    return Object.assign(oldOffer, offer);
если offer не найден, будет ошибка. Нужна проверка на undefined (find вернет undefined если не найдет элемент)

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/data-service/search.js
> +  findAll(searchText) {
Это обычно называют просто find. Найти все -- звучит странно.

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
функция асинхронная. Promise.reject и Promise.resolve не нужны. 
return Promise.reject(err) аналогичен throw err;
return Promise.resolve(value) аналогичен return value;

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/lib/get-mock-data.js
> +    return Promise.resolve(data);
Тут тоже самое

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/lib/get-mock-data.js
> +    console.log(err);
Ошибки логируют через console.error

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/middlewares/comment-validator.js
> +  return next();
return тут не нужен. Он будет проигнорирован.

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/middlewares/offer-exists.js
> +  return next();
смотри комментарий выше

2021-01-31 19:57 UTC, tsapko3628 commented on src/service/middlewares/offer-validator.js
> +  next();
если не поставить return внутри if-а, выполнение продолжиться и вызовется функция next(); Либо вернуть res.status ... либо сделать `return ;` на следующей строк. Также можно добавить next() в блок else

2021-02-04 14:42 UTC, tyort commented on src/service/api/index.js
> +})();
Если по порядку:
1) в файле src/service/api/index.js

const router = async () => {
  const app = new Router();
  // ждем получения моковых данных Promise.resolve(data)
  const mockData = await getMockData();

  // запускаем контроллеры
  category(app, new CategoryService(mockData));
  search(app, new SearchService(mockData));

  // для класса-комментов аргумент в constructor не нужен
  // в методы класса попадают аргументы при запросе маршрута
  offer(app, new OfferService(mockData), new CommentService());

  return app;
};

module.exports = router;

2021-02-04 16:41 UTC, tyort commented on src/service/data-service/offer.js
> +    return Object.assign(oldOffer, offer);
Проверка есть в другом методе. Он как раз вызывается перед update в определенном маршруте

2021-02-07 21:50 UTC, merged